import assert from 'node:assert/strict'
import { readFileSync, existsSync } from 'node:fs'

const index = readFileSync(new URL('../src/index.ts', import.meta.url), 'utf8')
const routes = readFileSync(new URL('../src/routes.ts', import.meta.url), 'utf8')
const models = readFileSync(new URL('../src/features/models/routes.ts', import.meta.url), 'utf8')
const aiFactory = readFileSync(new URL('../src/features/models/ai-factory.ts', import.meta.url), 'utf8')
const updateFile = readFileSync(new URL('../src/features/files/routes.ts', import.meta.url), 'utf8')
const sessions = readFileSync(new URL('../src/features/sessions/routes.ts', import.meta.url), 'utf8')

assert.match(index, /registerRoutes\(app\)/)
assert.match(routes, /app\.post\('\/api\/assets\/upload', uploadAsset\)/)
assert.match(routes, /app\.post\('\/api\/images\/upload', uploadImage\)/)
assert.match(routes, /app\.get\('\/api\/assets\/object\/\*', getAsset\)/)
assert.match(routes, /app\.get\('\/api\/realtime\/:room'/)

assert.match(routes, /app\.post\('\/api\/chat\/stream', chatHandlerStream\)/)
assert.match(routes, /app\.use\('\/api\/admin\/\*'/)
assert.match(routes, /app\.get\('\/models', getModels\)/)
assert.ok(!/app\.(get|post|put|delete)\('\/(chat|sessions|session-messages|profile|list-publications|get-analytics|projects)/.test(routes))
assert.ok(!routes.includes("'/admin/"))
assert.ok(!existsSync(new URL('../../apps/web/src/api/vercel-client.ts', import.meta.url)))
assert.ok(!existsSync(new URL('../../apps/web/src/api/chat-static.ts', import.meta.url)))
assert.ok(!existsSync(new URL('../../apps/web/src/api/chat-stream.ts', import.meta.url)))
assert.ok(!models.includes('../lib/db'))
assert.ok(!aiFactory.includes('./db'))
assert.match(aiFactory, /OpenAICompatibleProvider/)
assert.ok(!updateFile.includes('../lib/db'))
assert.match(updateFile, /\.\/service/)
assert.ok(!sessions.includes('../lib/db'))
assert.match(sessions, /\.\/service/)
